apiVersion: batch/v1
kind: Job
metadata:
  name: jaeger-tenant-deploy
spec:
  activeDeadlineSeconds: 300
  template:
    metadata:
      name: jaeger-tenant-deploy
    spec:
      containers:
      - name: jaeger-tenant-deploy
        image: gcr.io/scp-engsrvperfdev-gcp/jaeger-deploy:latest
        imagePullPolicy: Always
        env:
        - name: CUSTOMER_NAME
          value: cust2
        - name: DOMAIN
          value: ingress.mon-team.perf-load.shoot.dev.k8s-hana.ondemand.com
        - name: STORAGE_TYPE
          value: elasticsearch
        - name: ES_HOST
          value: elasticsearch-master
        - name: CASSANDRA_HOST
          value: prod-cassandra
        - name: CASSANDRA_DATACENTER
          value: dc1
        - name: KAFKA_ENABLED
          value: true
        - name: KAFKA_BROKER
          value: jaeger-kafka:9092
        - name: KUBECONFIG
          value: /config/kube.yaml
        resources:
          {}
        volumeMounts:
          - name: kube
            mountPath: /config
            readOnly: true
      restartPolicy: Never
      volumes:
        - name: kube
          configMap:
            name: kube-config
