apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-deployer
  labels:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/instance: deployer
    app.kubernetes.io/component: server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: jaeger
      app.kubernetes.io/instance: deployer
      app.kubernetes.io/component: server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jaeger
        app.kubernetes.io/instance: deployer
        app.kubernetes.io/component: server
      name: jaeger-deployer
    spec:
      containers:
      - name: jaeger-deployer
        image: docker.io/arpitjindal1997/jaeger-deployer:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: web
          protocol: TCP
        resources:
          {}
        volumeMounts:
          - name: kube
            mountPath: /root/.kube
            readOnly: true
      restartPolicy: Always
      volumes:
        - name: kube
          configMap:
            name: kube-config
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-deployer
  labels:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/instance: deployer
    app.kubernetes.io/component: server
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: web
  selector:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/instance: deployer
    app.kubernetes.io/component: server
  type: LoadBalancer
