provisionDataStore:
  cassandra: false
  elasticsearch: false

tag: 1.17.0

storage:
  type: $STORAGE
  cassandra:
    keyspace: $TEMP
    host: $CASSANDRA_HOST
  kafka:
    brokers: [$KAFKA_BROKER]
    topic: $TEMP
  elasticsearch:
    host: $ELASTICSEARCH_HOST
    usePassword: false
    indexPrefix: $TEMP

cassandra:
  config:
    dc_name: $CASSANDRA_DC

ingester:
  enabled: $INGESTER_ENABLED
  resources:
    limits:
      cpu: 2
      memory: 2Gi
    requests:
      cpu: 1
      memory: 1024Mi

collector:
  resources:
    limits:
      cpu: 2
      memory: 2Gi
    requests:
      cpu: 1
      memory: 1024Mi

agent:
  enabled: false
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

query:
  enabled: true
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

spark:
  enabled: false
  resources: 
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi