provisionDataStore:
  cassandra: false
  elasticsearch: false

storage:
  type: cassandra
  cassandra:
    keyspace: temp
    host: cassandra-host
  kafka:
    brokers: [kafka-broker]
    topic: temp
  elasticsearch:
    host: elasticsearch-host
    usePassword: false

cassandra:
  config:
    dc_name: cassandra-dc

ingester:
  enabled: true
  resources: 
    limits:
      cpu: 2
      memory: 2Gi
    requests:
      cpu: 1
      memory: 1024Mi

collector:
  cmdlineParams:
    collector_grpc_tls: false
    collector_grpc_tls_cert: /tls/server.crt
    collector_grpc_tls_client: /tls/ca.crt
    collector_grpc_tls_key: /tls/server.key
  extraSecretMounts:
    - name: jaeger-tls
      mountPath: /tls
      readOnly: true
      secretName: temp-tls-config
  resources: 
    limits:
      cpu: 2
      memory: 2Gi
    requests:
      cpu: 1
      memory: 1024Mi

agent:
  enabled: false
  resources: 
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

query:
  resources: 
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

spark:
  enabled: false
  resources: 
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi